apiVersion: v1
kind: Service
metadata:
    name: bitcoind-rpc
spec:
  type: NodePort
  selector:
    app: bitcoind-testnet
  ports:
  - name: rpc
    port: 18332
    targetPort: 18332
    nodePort: 30032
